### PR TITLE
Add browserify support

### PR DESCRIPTION
**Pull request by cappslock**
There are a couple quick things that could be done to make this work with [Browserify](http://browserify.org/):

- When module.exports is present, use it to export the module instead of attaching it to global scope
- Specify "main" in package.json

This pull request does both of those, and passes all unit tests.

### CODE REVIEW

**Comment by schickling** [comment]
+1

**Comment by viljamis** [comment]
I’ll merge this during the evening!

**Comment by schickling** [comment]
Please make sure to increase the version number and publish it to NPM. :+1:

**Comment by cappslock** [comment]
Great, thanks. Let me know if I can help with anything.

**Comment by viljamis** [comment]
@cappslock Merged!

@schickling I tried to publish it, but it seems I don’t have the rights to do it! Getting:
```Error: Request was not authorized``` 

Anyway, I noticed that you’ve earlier published it there, so you might have to add me as an owner too?

**Comment by schickling** [comment]
Done!

**Comment by viljamis** [comment]
@schickling Thanks man!

**Pull request merged**
