### PR TITLE
Add back pointer events on mobile after fast repetitive touches

### LINKED ISSUE #145: `disable-pointer-events` not removed after fast touches
After tapping the menu toggle for a few times (3 is enough) in quick successtion the `disable-pointer-events` class stays on `body` element. Nothing responds touch events after that. Case: https://froont.com/click/responsive-nav-problem

### PR DESCRIPTION
**Pull request by bez4pieci**
Fixes #145

### CODE REVIEW

**Comment by viljamis** [comment]
@bez4pieci Thanks for looking into this! I’ll test this soon and do a merge tomorrow if everything is working :)

**Comment by viljamis** [comment]
@bez4pieci I’ve been looking into this today and it seems like I can further simplify the whole toggle logic quite a lot. I have a new version ready with your changes merged, but I still want to test it tomorrow with few more devices before pushing a new version out.

**Comment by bez4pieci** [comment]
@viljamis, great to hear :+1:! would be great to avoid adding/removing classes to `<body>` altogether!

**Comment by viljamis** [comment]
@bez4pieci  Turns out I could actually remove the whole pointer-events functionality yesterday evening completely while still making the ghost click issue to not happen anymore on Android 2.3 and under. Just pushed out a new version!

**Pull request merged**
